fix(api): deploy failed due to prisma client
```
Error: @prisma/client did not initialize yet.
Please run "prisma generate" and try to import it again.
```